services:
  marquee:
    image: ghcr.io/ngttech/marquee:latest
    container_name: marquee
    ports:
      - "3000:3000"
    volumes:
      - /volume2/apps/marquee:/app/data
    restart: unless-stopped
